### PR TITLE
Adding support for naive (no x509/pkix required) issuance of certs/keys from a PKI backend

### PR DESCRIPTION
**Pull request by robison**

### CODE REVIEW

**Comment by robison** [comment]
New tests:

```
=== RUN   TestCertIssuance
2019/07/29 10:31:00 Certificate or private key output path is empty, will not attempt to get certificate
2019/07/29 10:31:00 Getting certificate from vault...
2019/07/29 10:31:00 Getting certificate from vault...
2019/07/29 10:31:00 Getting certificate from vault...
2019/07/29 10:31:00 Getting certificate from vault...
2019/07/29 10:31:00 Getting certificate from vault...
2019/07/29 10:31:00 Error requesting cert from Vault: Error making API request.

URL: PUT https://127.0.0.1:62322/v1/test_intermediate_authority_T2/issue/wrong-role
Code: 400. Errors:

* unknown role: wrong-role
2019/07/29 10:31:00 Getting certificate from vault...
2019/07/29 10:31:00 Error while writing cert data: could not write certificate to file '/dev/urandom': write /dev/urandom: operation not permitted
2019/07/29 10:31:00 Getting certificate from vault...
2019/07/29 10:31:00 Error while writing cert data: could not write certificate to file '/dev/urandom': write /dev/urandom: operation not permitted
--- PASS: TestCertIssuance (0.02s)
PASS
coverage: 93.9% of statements
```

**Comment by robison** [comment]
Fwiw, compilation on macOS yields a binary that's only ~25k larger.

**Comment by robison** [comment]
Resolves #2

**Comment by broamski** [comment]
This purely a thought exercise, is there a situation where a system/service needs to obtain more than 1 certificate?

Multiples of the same flag? Input a map? I'm trying to think of both an example and an elegant way to accomplish this.

**Comment by robison** [comment]
Rebased and retested.

```
 $ git log -1
commit cc66ff6fb3564bd9410da6cd317307be90512e8a (HEAD -> add-pki-support)
Author: robison jacka <robison@packetized.io>
Date:   Sun Jul 28 23:28:01 2019 -0700

    Adding support for naive (no x509/pkix required) issuance of certs/keys from a PKI backend
 $ make test
go test -cover -count=1 -v github.com/cruise-automation/daytona/cmd/daytona github.com/cruise-automation/daytona/pkg/auth github.com/cruise-automation/daytona/pkg/config github.com/cruise-automation/daytona/pkg/helpers/testhelpers github.com/cruise-automation/daytona/pkg/pki github.com/cruise-automation/daytona/pkg/secrets
?   	github.com/cruise-automation/daytona/cmd/daytona	[no test files]
=== RUN   TestAuthPanic
2019/10/07 14:42:59 Checking for an existing, valid vault token
2019/10/07 14:43:03 Invalid token:  Get nan/v1/auth/token/lookup-self: unsupported protocol scheme ""
2019/10/07 14:43:03 No token found in VAULT_TOKEN env, checking path
2019/10/07 14:43:03 Can't read an existing token at "".
2019/10/07 14:43:03 No token found in "", trying to re-authenticate
2019/10/07 14:43:03 Authentication will be attempted for 1 seconds.
--- PASS: TestAuthPanic (3.53s)
=== RUN   TestServiceAuth
--- PASS: TestServiceAuth (0.00s)
=== RUN   TestFetchVaultToken
--- PASS: TestFetchVaultToken (0.00s)
=== RUN   TestFetchVaultTokenFailure
--- PASS: TestFetchVaultTokenFailure (0.00s)
=== RUN   TestInvalidToken
2019/10/07 14:43:03 Invalid token:  Error making API request.

URL: GET https://127.0.0.1:52814/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied
--- PASS: TestInvalidToken (0.00s)
=== RUN   TestValidToken
--- PASS: TestValidToken (0.00s)
=== RUN   TestFileToken
2019/10/07 14:43:03 Found an existing token at /var/folders/_h/xsr1gyjx1sj_vg2q3_ch5bsm0000gp/T/daytona-test343557370
--- PASS: TestFileToken (0.00s)
PASS
coverage: 23.4% of statements
ok  	github.com/cruise-automation/daytona/pkg/auth	3.701s	coverage: 23.4% of statements
=== RUN   TestInvalidConfig
--- PASS: TestInvalidConfig (0.00s)
PASS
coverage: 28.6% of statements
ok  	github.com/cruise-automation/daytona/pkg/config	0.132s	coverage: 28.6% of statements
?   	github.com/cruise-automation/daytona/pkg/helpers/testhelpers	[no test files]
=== RUN   TestSingleDomainCertIssuance
2019/10/07 14:42:59 Certificate or private key output path is empty, will not attempt to get certificate
2019/10/07 14:42:59 Getting certificate from vault...
2019/10/07 14:42:59 Getting certificate from vault...
--- PASS: TestSingleDomainCertIssuance (0.01s)
=== RUN   TestMultipleDomainCertIssuance
2019/10/07 14:42:59 Getting certificate from vault...
2019/10/07 14:42:59 Getting certificate from vault...
--- PASS: TestMultipleDomainCertIssuance (0.00s)
=== RUN   TestCertIssuanceErrors
2019/10/07 14:42:59 Getting certificate from vault...
2019/10/07 14:42:59 Error requesting cert from Vault: Error making API request.

URL: PUT https://127.0.0.1:52797/v1/test_intermediate_authority_T2/issue/wrong-role
Code: 400. Errors:

* unknown role: wrong-role
2019/10/07 14:42:59 Getting certificate from vault...
2019/10/07 14:42:59 Error while writing cert data: could not write private key to file '/var/folders/_h/xsr1gyjx1sj_vg2q3_ch5bsm0000gp/T/pki-test-849374525': open /var/folders/_h/xsr1gyjx1sj_vg2q3_ch5bsm0000gp/T/pki-test-849374525: permission denied
2019/10/07 14:42:59 Getting certificate from vault...
2019/10/07 14:42:59 Error while writing cert data: could not write certificate to file '/var/folders/_h/xsr1gyjx1sj_vg2q3_ch5bsm0000gp/T/pki-test-904068984': open /var/folders/_h/xsr1gyjx1sj_vg2q3_ch5bsm0000gp/T/pki-test-904068984: permission denied
--- PASS: TestCertIssuanceErrors (0.00s)
PASS
coverage: 100.0% of statements
ok  	github.com/cruise-automation/daytona/pkg/pki	0.252s	coverage: 100.0% of statements
=== RUN   TestParallelReader
--- PASS: TestParallelReader (0.00s)
=== RUN   TestSecretPath
2019/10/07 14:42:59 Starting secret fetch
2019/10/07 14:42:59 Wrote 2 secrets to /var/folders/_h/xsr1gyjx1sj_vg2q3_ch5bsm0000gp/T/secret-path-018403198
--- PASS: TestSecretPath (0.00s)
=== RUN   TestSecretDirectPath
2019/10/07 14:42:59 Starting secret fetch
2019/10/07 14:42:59 Wrote secret to /var/folders/_h/xsr1gyjx1sj_vg2q3_ch5bsm0000gp/T/secret-direct-path-638367941
--- PASS: TestSecretDirectPath (0.00s)
=== RUN   TestSecretAWalk
2019/10/07 14:42:59 Starting secret fetch
2019/10/07 14:42:59 Starting iteration on secret/path/common
2019/10/07 14:42:59 Wrote 4 secrets to /var/folders/_h/xsr1gyjx1sj_vg2q3_ch5bsm0000gp/T/secret-walk-206899552
--- PASS: TestSecretAWalk (0.00s)
PASS
coverage: 77.0% of statements
ok  	github.com/cruise-automation/daytona/pkg/secrets	0.271s	coverage: 77.0% of statements
 $
```

**Comment by robison** [comment]
Also, this fixes a minor regression with the `Makefile`, where an empty line was not included after the opening docblock, which caused this:

```
 $ make test
Makefile:14: *** missing separator.  Stop.
 $
```

**Pull request merged**
